### ISSUE TITLE
Consider reimplementation in %popular programming language%

### ISSUE THREAD

**Issue by fungiboletus** [polytechnice-si/5A-Microservices-Integration#1]
It's not too late, only need to change the .gitignore file to move away from Java !

**Comment by rediscooler** [comment]
Or is it ? <insert_epic_sound_effect>

**Comment by mosser** [comment]
Please insert here %any benefits% of doing so (excepting being hype) with respect to the focus of a graduate course, i.e., understanding the concepts to be able to survive to the next fashion?

**Comment by fungiboletus** [comment]
If nobody teaches Java, maybe people will stop using Java.

**Comment by mosser** [comment]
![troll_detected](http://orig12.deviantart.net/a4aa/f/2010/065/2/a/troll_detected_by_hunter_flood.png)

**Comment by fungiboletus** [comment]
![troll](https://user-images.githubusercontent.com/45740/28465541-6ece80c6-6e29-11e7-98f7-7558dcd8ed06.jpg)

:norway: A Norwegian one, they are terrible.
